### ISSUE TITLE
plugin doesn't see devices after update to 2.40.2

### ISSUE THREAD

**Issue by OleksandrLukhaninGL** [rokucommunity/vscode-brightscript-language#484]
plugin doesn't see devices after update to 2.40.2. When I am trying to deploy the app as usual there is nothing on OUTPUT and DEBUG CONSOLE as well.  Also "bsc-0.64.3" and "Remote" icons disappeared from the right bottom corner. 
All works fine again after revert to previous 2.40.1 version.

**Comment by TwitchBronBron** [comment]
Can you look in the "BrightScript Log" "BrightScript Extension" and "BrighterScript Language Server" output channels to see if there is any type of stack trace that might give more information as to what is causing the crash?

**Comment by OleksandrLukhaninGL** [comment]
When version 2.40.2 installed there are not any "BrightScript Log" "BrightScript Extension" and "BrighterScript Language Server" in the list. But I could provide output from the "Extention host": 
2023-05-18 01:01:32.699 [info] ExtensionService#_doActivateExtension RokuCommunity.brightscript, startup: true, activationEvent: 'workspaceContains:**/manifest,**/bsconfig.json'
2023-05-18 01:01:32.786 [error] Activating extension RokuCommunity.brightscript failed due to an error:
2023-05-18 01:01:32.786 [error] Error: Cannot find module 'request'
Require stack:
- /home/oleksandr/.vscode/extensions/rokucommunity.brightscript-2.40.2/dist/BrightScriptCommands.js
- /home/oleksandr/.vscode/extensions/rokucommunity.brightscript-2.40.2/dist/extension.js
- /snap/code/129/usr/share/code/resources/app/out/vs/loader.js
- /snap/code/129/usr/share/code/resources/app/out/bootstrap-amd.js
- /snap/code/129/usr/share/code/resources/app/out/bootstrap-fork.js
- 
	at Module._resolveFilename (node:internal/modules/cjs/loader:1010:15)
	at s._resolveFilename (node:electron/js2c/utility_init:2:2740)
	at Module._load (node:internal/modules/cjs/loader:858:27)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:29948)
	at h._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:26698)
	at I._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (/snap/code/129/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/oleksandr/.vscode/extensions/rokucommunity.brightscript-2.40.2/dist/BrightScriptCommands.js:4:17)
	at u._compile (/snap/code/129/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:29948)
	at h._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:26698)
	at I._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at g (/snap/code/129/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/oleksandr/.vscode/extensions/rokucommunity.brightscript-2.40.2/dist/extension.js:11:32)
	at u._compile (/snap/code/129/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1243:10)
	at Module.load (node:internal/modules/cjs/loader:1058:32)
	at Module._load (node:internal/modules/cjs/loader:893:12)
	at f._load (node:electron/js2c/asar_bundle:2:13330)
	at b._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:29948)
	at h._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:26698)
	at I._load (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:24489)
	at Module.require (node:internal/modules/cjs/loader:1082:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.i [as __$__nodeRequire] (/snap/code/129/usr/share/code/resources/app/out/vs/loader.js:5:98)
	at v.rb (/snap/code/129/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:126:27962)
	at async Promise.all (index 0)
2023-05-18 01:01:32.786 [info] Eager extensions activated
2023-05-18 01:01:32.831 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'

I hope it'll help.

**Comment by OleksandrLukhaninGL** [comment]
Also the same problem with this version(2.40.2) there is on my home PC on Windows. Also the reverting to 2.40.1 helps.

**Comment by TwitchBronBron** [comment]
Ah, perfect. I found the issue, and am building a new release right now. You should see this change in v2.40.3.
